#!/usr/bin/env bash
# exitmap DNS Health - Cloudflare Pages Deploy
# Generates wrangler.toml and deploys frontend with Pages Functions.
#
# Usage:
#   ./scripts/pages-deploy.sh              # Deploy to Cloudflare Pages
#   ./scripts/pages-deploy.sh --dry-run    # Generate wrangler.toml only

set -euo pipefail

# Source shared functions and initialize paths
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"
init_paths

err() { log_error "$1"; exit 1; }

[[ "${1:-}" == "--help" || "${1:-}" == "-h" ]] && {
    echo "Usage: $0 [--dry-run]"
    echo ""
    echo "Generates wrangler.toml from config.env and deploys to Cloudflare Pages."
    echo ""
    echo "Required in config.env:"
    echo "  CLOUDFLARE_ACCOUNT_ID  - Cloudflare account ID"
    echo "  CLOUDFLARE_API_TOKEN   - Cloudflare API token with Pages permissions"
    echo ""
    echo "Optional:"
    echo "  PAGES_PROJECT_NAME     - Pages project name (default: exitmap-dns)"
    echo "  STORAGE_ORDER          - Backend order: do,r2 or r2,do (default: do,r2)"
    echo "  R2_BUCKET              - R2 bucket name"
    echo "  DO_SPACES_BUCKET       - DO Spaces bucket name"
    echo "  CUSTOM_DOMAIN          - Custom domain (e.g., exitdns.1aeo.com)"
    exit 0
}

DRY_RUN=$([[ "${1:-}" == "--dry-run" ]] && echo true || echo false)

# Load config
load_config || err "config.env not found. Copy config.env.example first."

# Check dependencies
require_cmd node || err "Node.js required (apt install nodejs npm)"
require_cmd npm || err "npm required"

# Validate required config
[[ -n "${CLOUDFLARE_ACCOUNT_ID:-}" && "$CLOUDFLARE_ACCOUNT_ID" != "your_account_id" ]] || {
    # Try loading from ~/.config/cloudflare
    [[ -f "$HOME/.config/cloudflare/credentials" ]] && source "$HOME/.config/cloudflare/credentials"
}
[[ -n "${CLOUDFLARE_ACCOUNT_ID:-}" ]] || err "CLOUDFLARE_ACCOUNT_ID not set in config.env"

[[ -n "${CLOUDFLARE_API_TOKEN:-}" && "$CLOUDFLARE_API_TOKEN" != "your_api_token" ]] || {
    [[ -f "$HOME/.config/cloudflare/api_token" ]] && source "$HOME/.config/cloudflare/api_token"
}
[[ -n "${CLOUDFLARE_API_TOKEN:-}" ]] || err "CLOUDFLARE_API_TOKEN not set"

# Defaults
: "${PAGES_PROJECT_NAME:=exitmap-dns}"
: "${STORAGE_ORDER:=do,r2}"
: "${WRANGLER_COMPATIBILITY_DATE:=2025-01-01}"
: "${CACHE_TTL_LATEST:=60}"
: "${CACHE_TTL_HISTORICAL:=31536000}"
: "${DO_SPACES_REGION:=nyc3}"
: "${DO_SPACES_CDN:=false}"

# Build DO URL if not set
if [[ "${DO_ENABLED:-false}" == "true" && -z "${DO_SPACES_URL:-}" && -n "${DO_SPACES_BUCKET:-}" ]]; then
    CDN=$([[ "$DO_SPACES_CDN" == "true" ]] && echo ".cdn" || echo "")
    DO_SPACES_URL="https://${DO_SPACES_BUCKET}.${DO_SPACES_REGION}${CDN}.digitaloceanspaces.com"
fi

# Generate wrangler.toml
WRANGLER_FILE="$DEPLOY_DIR/wrangler.toml"
log "Generating wrangler.toml..."

{
    cat <<EOF
# Generated by pages-deploy.sh - Do not edit manually
# Regenerate with: ./scripts/pages-deploy.sh --dry-run

name = "${PAGES_PROJECT_NAME}"
compatibility_date = "${WRANGLER_COMPATIBILITY_DATE}"
pages_build_output_dir = "pages-static"

[vars]
STORAGE_ORDER = "${STORAGE_ORDER}"
CACHE_TTL_LATEST = "${CACHE_TTL_LATEST}"
CACHE_TTL_HISTORICAL = "${CACHE_TTL_HISTORICAL}"
EOF

    if [[ -n "${DO_SPACES_URL:-}" ]]; then
        echo "DO_SPACES_URL = \"${DO_SPACES_URL}\""
    fi
    
    echo ""
    
    if [[ "${R2_ENABLED:-false}" == "true" && -n "${R2_BUCKET:-}" ]]; then
        cat <<EOF
[[r2_buckets]]
binding = "EXITMAP_BUCKET"
bucket_name = "${R2_BUCKET}"
EOF
    else
        echo "# R2 disabled or R2_BUCKET not set"
    fi
} > "$WRANGLER_FILE"

log_success "Generated: $WRANGLER_FILE"

# Prepare static directory (index.html only - JSON served from storage)
STATIC_DIR="$DEPLOY_DIR/pages-static"
mkdir -p "$STATIC_DIR"
cp -f "$DEPLOY_DIR/public/index.html" "$STATIC_DIR/"

# Copy functions
mkdir -p "$STATIC_DIR/../functions"
cp -f "$DEPLOY_DIR/functions/[[path]].js" "$STATIC_DIR/../functions/" 2>/dev/null || true

log "Project: $PAGES_PROJECT_NAME | Storage: $STORAGE_ORDER"
[[ -n "${DO_SPACES_URL:-}" ]] && log "DO: $DO_SPACES_URL"
[[ -n "${R2_BUCKET:-}" ]] && log "R2: $R2_BUCKET"
log "Static: $(du -sh "$STATIC_DIR" 2>/dev/null | cut -f1 || echo "N/A")"

if [[ "$DRY_RUN" == "true" ]]; then
    log "Dry run - skipping deploy"
    echo ""
    echo "Generated wrangler.toml:"
    echo "========================"
    cat "$WRANGLER_FILE"
    exit 0
fi

# Deploy
export CLOUDFLARE_API_TOKEN="$CLOUDFLARE_API_TOKEN"
export CLOUDFLARE_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID"
cd "$DEPLOY_DIR"

WRANGLER=$(command -v wrangler 2>/dev/null || echo "npx wrangler")
log "Deploying to Cloudflare Pages..."

$WRANGLER pages deploy "$STATIC_DIR" \
    --project-name="$PAGES_PROJECT_NAME" \
    --branch=production \
    --commit-dirty=true

echo ""
log_success "Deployed: https://${PAGES_PROJECT_NAME}.pages.dev"
[[ -n "${CUSTOM_DOMAIN:-}" ]] && log_success "Custom: https://$CUSTOM_DOMAIN"
